##################################################################
#' chimericStats
#'
#' @param chimericDT : Data table of chimeric junctions as provided by
#' STAR aligner
#'
#' @description
#'   Number of chimeric entries
#'   Number of unique junctions
#'   Frequency of most abundant junction
#'   Number of backsplice vs other junctions
#'
#' @export
chimericStats <- function(chimericDT)
{

  total_rows <- nrow(chimericDT)
  # Number of unique junctions
  tableSummary <- table(data_set$BSjuncName)
  n_UniqueJunctions <- length(tableSummary)

 return(list(totalRows= total_rows, uniqueJunctionNum = n_UniqueJunctions))
}
 

####################################################################
#' loadSTAR_chimeric
#'
#' @description
#' Loads chimeric output file from the STAR aligner and returns a list containing
#' three items (a data table, alignment stats and command line).
#'
#' @param filename :  filename of the STAR chimeric output file.
#'             Can be gzipped
#' @param ID_index :  An index (single integer) which will be added
#' as a separate column in the returned data table. Useful when
#' collating multiple files into one large matrix like object.
#' @param returnColIdx : Numeric index of columns to return. Default 1:15
#'
#' @details  :
#'
#' Reads in a text or gzipped chimeric output file generated by the STAR aligner. Function
#' automatically detects if the last two lines contains meta-data (produced from STAR 2.7)
#' onwards.
#'
#' Returns a list of containing three items: (1) data_set (2) alignmentStats and (3) commandLine.
#'
#' The column names of data_set are defined as
#' c("chromDonor","startDonor","strandDonor", "chromAcceptor",
#' "startAcceptor","strandAcceptor","JuncType", "RepeatLength_L",
#' "RepeatLength_R",  "ReadName","FirstBase_1stSeq","CIGAR_1stSeg",
#' "FirstBase_2ndSeq","CIGAR_2ndSeg", "Multimapping")
#'
#' If ID_index is set to a value greater than 0 then an additional column called
#' "DataSet" is created.
#'
#' Columns can be subsetted by defining returnColIdx with an integer value that correspond
#' to order of column names listed above.
#'
#'
#' @export
loadSTAR_chimeric <- function(filename=NULL, ID_index = 0, returnColIdx=1:21)
{ messg <- NULL
  if (is.null(filename))
  { messg <- "No file name provided. Cannot continue"  }

  if(length(setdiff(returnColIdx, 1:21)) > 0)
  { messg <- "returnColIdx contains out of bound index. Please check and try again"  }

  if (! is.numeric(version) && ! is.numeric(ID_index))
  { messg <- "version or ID_index is not numeric. Please modify and try again" }

  if (! is.null(messg))
  {
    warning(messg)
    return(NULL)
  }

  # read in file and check has correct number of columns
  data_set <- data.table::fread(filename, sep="\t", fill=TRUE)
  total_rows <- nrow(data_set)
  columnNumber <- ncol(data_set)
  if ((columnNumber < 14) || (columnNumber > 21))
  {
    warning(paste0("Unexpected number of columns in ", filename," cannot process."))
    return(NULL)
  }
  # Check what columns can be accessed, which is defined by number of columns
  maxColRange <- 1:columnNumber


  if(length(setdiff(returnColIdx, maxColRange)) > 0)
  { messg <- paste0("Number of columns available is smaller than what was specified. ",
        "Suspect using data from old version of STAR aligner (pre 2.7.3). ",
        "Please try a smaller range in returnColIdx (perhaps 1:14 or 1:15).")
    warning(messg)
    return(NULL)
  }


  # prepare column labels
  colnameIDs <- c("chromDonor","startDonor","strandDonor", "chromAcceptor",
                "startAcceptor","strandAcceptor","JuncType", "RepeatLength_L",
                "RepeatLength_R",  "ReadName","FirstBase_1stSeq","CIGAR_1stSeg",
                "FirstBase_2ndSeq","CIGAR_2ndSeg", "Num_chim_aln",
                "max_poss_aln_score", "non_chim_aln_score", "this_chim_aln_score",
                "bestall_chim_aln_score", "PEmerged_bool", "readgrp"
                )
  numericColIDs <- colnameIDs[c(2,5,7,8,9,11,13,15:20)]
  colnameIDs <- colnameIDs[returnColIdx]


  # Check last two rows to determine if data generated from STAR 2.7 or above.
  # If so need to re-format data
  alignmentStats = NULL
  commandLine = NULL
  if (grep(pattern = "Nreads",x = data_set[total_rows,1]))
  { # Collect meta data from last two rows and then remove
    alignmentStats <- paste(data_set[total_rows,],collapse = " ")
    commandLine <- paste(data_set[total_rows -1,],collapse = " ")
    total_rows <- total_rows - 2
    data_set <- data_set[1:total_rows,]
  }
  # See if data has header, if so remove. This was introduced in STAR 2.7.3
  if(data_set[1,1] == "chr_donorA")
  { data_set <- data_set[-1,]

  }

  data_set <- data_set[,returnColIdx]
  data.table::setnames(data_set,returnColIdx,colnameIDs)

  # Fix up numeric columns which are converted to characters if alignmentStats not null
  if (! is.null(alignmentStats))
  { colsToConvert<- intersect(colnameIDs, numericColIDs)
    for (i in colsToConvert)
    { data_set[[i]] <- as.numeric(data_set[[i]])  }
  }

  # General unique lookup ID
  data_set$BSjuncName <- paste(data_set$chromDonor,data_set$startDonor,data_set$chromAcceptor, data_set$startAcceptor,sep="_")
  if (ID_index > 0)
  {  data_set$DataSet <-  ID_index }	# This adds an index to identify the file
  return(list(data_set=data_set, alignmentStats=alignmentStats, commandLine=commandLine))

}